# Generated by Django 4.1.3 on 2022-12-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0002_currency_income_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_api.currency', verbose_name='Income currency'),
        ),
    ]
