# Generated by Django 4.1.3 on 2022-12-06 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_api', '0004_expense_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget_api.currency', verbose_name='Expense currency'),
        ),
    ]
